--DATA LOADING FROM AMAZON S3 TO STAGING

CREATE WAREHOUSE IF NOT EXISTS SANFORD_WH
WAREHOUSE_SIZE = 'XSMALL'
WAREHOUSE_TYPE = 'STANDARD';

CREATE OR REPLACE DATABASE SANFORD_EXPORTS;
CREATE OR REPLACE SCHEMA  SANFORD_EXPORTS.RAW;
CREATE OR REPLACE SCHEMA  SANFORD_EXPORTS.MARTS;

CREATE OR REPLACE FILE FORMAT SANFORD_EXPORTS.RAW.FF_CSV
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
NULL_IF = ('\\N','NULL','');

USE  ROLE ACCOUNTADMIN;
CREATE OR REPLACE STORAGE INTEGRATION s3_int
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::905760242596:role/shwetha-snowflake-role'
STORAGE_ALLOWED_LOCATIONS = ('s3://shwetha-yfinance-raw/');

USE  ROLE SYSADMIN;
DESC STORAGE INTEGRATION s3_int;

CREATE OR REPLACE STAGE SANFORD_EXPORTS.RAW.S3_STAGE
URL = 's3://shwetha-yfinance-raw/'
STORAGE_INTEGRATION = s3_int;

--CRAETING RAW DATA TABLES
CREATE OR REPLACE TABLE RAW_EXPORTS (
SPECIES STRING,
PRODUCT STRING,
COUNTRY STRING,
VOLUME NUMBER,
VALUE NUMBER,
SOURCE_FILE STRING,
FISCAL_YEAR STRING,
LOAD_TIMESTAMP TIMESTAMP
);

COPY INTO RAW_EXPORTS
FROM (select 
$1::STRING AS SPECIES,
$2::STRING AS PRODUCT,
$3::STRING AS COUNTRY,
$4::NUMBER AS VOLUME,
$5::NUMBER AS VALUE,
METADATA$FILENAME AS SOURCE_FILE,
'20'||SPLIT_PART(REPLACE(METADATA$FILENAME,'.csv',''),'-',5) AS FISCAL_YEAR,
CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM @S3_STAGE
(FILE_FORMAT => FF_CSV));

--CLEANING THE DATA--
DELETE FROM SANFORD_EXPORTS.RAW.RAW_EXPORTS
WHERE VOLUME IS NULL OR VALUE IS NULL OR COUNTRY IS NULL OR PRODUCT IS NULL OR SPECIES IS NULL;

UPDATE SANFORD_EXPORTS.RAW.RAW_EXPORTS
SET COUNTRY=
    CASE 
        WHEN COUNTRY LIKE '%,%' 
        THEN CONCAT(
                TRIM(SPLIT_PART(COUNTRY, ',', 2)), ' ',
                TRIM(SPLIT_PART(COUNTRY, ',', 1))
             )
        ELSE COUNTRY 
    END;


--CREATING DIMENSION TABLES
CREATE OR REPLACE TABLE SANFORD_EXPORTS.MARTS.DIM_COUNTRY AS
SELECT DISTINCT ABS(MOD(HASH(TRIM(country)), 1000000)) AS COUNTRY_ID , TRIM(COUNTRY) AS COUNTRY_NAME 
FROM SANFORD_EXPORTS.RAW.RAW_EXPORTS;

CREATE OR REPLACE TABLE SANFORD_EXPORTS.MARTS.DIM_SPECIES AS
SELECT DISTINCT ABS(MOD(HASH(TRIM(SPECIES)), 1000000)) AS SPECIES_ID , TRIM(SPECIES) AS SPECIES_NAME   FROM  SANFORD_EXPORTS.RAW.RAW_EXPORTS;


CREATE OR REPLACE TABLE SANFORD_EXPORTS.MARTS.DIM_PRODUCT AS
SELECT DISTINCT ABS(MOD(HASH(TRIM(PRODUCT)), 1000000)) AS PRODUCT_ID , TRIM(PRODUCT) AS PRODUCT_NAME   FROM  SANFORD_EXPORTS.RAW.RAW_EXPORTS;


--CREATING FACT TABLE
CREATE OR REPLACE TABLE SANFORD_EXPORTS.MARTS.FACT_EXPORTS AS
SELECT
    s.SPECIES_ID,
    p.PRODUCT_ID,
    c.COUNTRY_ID,
    R.FISCAL_YEAR,
    r.VOLUME,
    r.VALUE
FROM SANFORD_EXPORTS.RAW.RAW_EXPORTS r
JOIN SANFORD_EXPORTS.MARTS.DIM_SPECIES s ON TRIM(r.SPECIES) = s.SPECIES_NAME
JOIN SANFORD_EXPORTS.MARTS.DIM_PRODUCT p ON TRIM(r.PRODUCT) = p.PRODUCT_NAME
JOIN SANFORD_EXPORTS.MARTS.DIM_COUNTRY c ON TRIM(r.COUNTRY) = c.COUNTRY_NAME;

